config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :users, except: [:new]
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :messages ,only: [:create,:index]

  mount ActionCable.server, at: '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body ,presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  validates :email ,presence: true ,uniqueness: true
  validates :name ,presence:  true, uniqueness: true

  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      begin
        @current_user = User.find(session[:user_id])
      rescue
        session[:user_id]=nil
      end
    end
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must login for perfom action"
      redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = Message.new
    @messages = Message.all
    @users = User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(params.require(:message).permit(:body))
    if message.save
      ActionCable.server.broadcast "chatroom_channel", msg: message_render(message)
    end
  end

  private
  def message_render(message)
    render(partial: 'message',locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "user logged in"
      session[:user_id] = user.id
      redirect_to users_path
    else
      flash.now[:danger] ="invalid username and password"
      render 'new'
    end

  end

  def destroy
    session[:user_id] =nil
    flash[:success] = "user logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:new ,:create]
  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def create
    @user =User.new(users_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def show

  end

  private
  def users_params
    params[:user].permit(:name,:email,:password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options = {size: 200})
    email_address=user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url,alt: user.name,class: "rounded shadow mx-auto d-block")
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
    <div class="container">
      <div class="chatroom">
        <div class="chatroom-chat mt-1" id="messages">
         <%= render  @messages %>
        </div>
        <%= form_with(model: @message, class: "form-inline ml-5 mr-5",url: messages_path,remote: true) do |f| %>
            <label class="sr-only" for="inlineFormInputName2">Msg</label>
          <%= f.text_field :body, class: "form-control mb-2 mr-sm-2",placeholder: "enter the msg" ,id: "inlineFormInputName2"%>
          <%= f.submit("submit",class: "btn btn-primary mb-2 " ,id: "submit-btn-msg")%>
        <% end %>
      </div>
        <div class="card users">
          <div class="card-header">
            Users
          </div>
          <ul class="list-group list-group-flush">
            <% @users.each do |user| %>
              <li class="list-group-item"><%= user.name %></li>
              <%end %>
          </ul>
        </div>
    </div>
</body>
</html>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'WhatsApp',root_path , class: "navbar-brand" ,id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Bloggers',users_path,class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'View Profile',user_path(current_user), class:"dropdown-item"%>
            <%= link_to 'Edit Profile',edit_user_path(current_user), class:"dropdown-item"%>
            <%= link_to 'Delete Profile',user_path(current_user),class:"dropdown-item text-danger",method: :delete,data: {confirm: "Are You Sure Want To Delete Your Account?"} %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'logout',logout_path,method: :delete,class: "nav-link" %>
        </li>
      <%else %>
        <li class="nav-item">
          <%= link_to 'Login',login_path,class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'SignUp',signup_path,class: "nav-link" %>
        </li>
      <%end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whatsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/nav' %>
    <% flash.each do |name,msg|%>
    <div class="alert alert-<%=name%> alert-dismissible fade show align-self-center w-75" role="alert">
      <%=msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p class="ml-4"> <strong><%=message.user.name%></strong> : <%=message.body %></p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">

    <%@user.errors.full_messages.each do |msg| %>
      <li> <%=msg %></li>
    <%end %>
  </div>
<% end %>
<div class="container">
  <%= form_with(model: @user,local: true,class: "shadow p-5 m-1 bg-info rounded") do |f| %>
    <div class="form-group row ">
      <%= f.label :username, class: "col-2 col-form-label" %></br>
      <div class="col-10">
        <%= f.text_field :name, class: "form-control",placeholder: "username" %>
      </div>
    </div>

    <div class="form-group row ">
      <%= f.label :email, class: "col-2 col-form-label" %></br>
      <div class="col-10">
        <%= f.text_field :email, class: "form-control",placeholder: "email" %>
      </div>
    </div>

    <div class="form-group row ">
      <%= f.label :password, class: "col-2 col-form-label" %></br>
      <div class="col-10">
        <%= f.password_field :password, class: "form-control",placeholder: "password" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.submit(@user.new_record? ? "SignUp": "Update Account" ,class: "btn btn-outline-light btn-lg m-auto" )%>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="container">
  <h1 class="text-center">All Bloggers</h1>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
  <% @users.each do |user| %>
    <div class="card text-center align-self-center w-75 m-auto shadow mb-5 bg-white rounded">
      <div class="card-header">
        <%= user.name%>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to gravatar_for(user),user%></h5>
        <%=link_to 'Show Profile',user_path(user),class:"btn btn-outline-success" %>
        <% if logged_in? && user == current_user %>
          <%=link_to 'Edit Profile',edit_user_path(user),class:"btn btn-outline-info" %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        joined <%=time_ago_in_words(user.created_at) %> ago
      </div>
    </div><br><br>
  <%end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%=@user.name %>'s profile</h1>

<%=gravatar_for @user%>
<div class="text-center mt-4">
  <% if logged_in? && @user == current_user %>
    <%=link_to 'Edit Profile',edit_user_path(@user),class: "btn btn-outline-info" %>
  <% end %>
</div>